version: "3.9"

#name: atlas

networks:
  atlas-network:
    external: true

volumes:
  atlas_mongodata:        # MongoDB data (isolé)
  atlas_mongo_backup:     # MongoDB backups
  atlas_miniodata:        # MinIO data
  atlas_minio_backup:     # MinIO backups
  atlas_chromadb_data:    # ChromaDB data

services:
  mongo:
    image: mongo:7
    restart: always
    container_name: mongo-atlas
    environment:
      MONGO_INITDB_DATABASE: atlas
      MONGO_INITDB_ROOT_USERNAME: atlas
      MONGO_INITDB_ROOT_PASSWORD: 'atlasP@ssWord25#!'
      MONGO_PASSWORD: 'atlasP@ssWord25#!'
    volumes:
      - atlas_mongodata:/data/db
      - atlas_mongo_backup:/backups
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - atlas-network
    ports:
      - "27027:27017"  # Mongo écoute en interne sur 27017 (best practice)

  minio:
    image: minio/minio
    restart: always
    container_name: minio-atlas
    environment:
      MINIO_ROOT_USER: atlas
      MINIO_ROOT_PASSWORD: 'atlasP@ssWord25#!'
    command: server /data --console-address ":9001"
    volumes:
      - atlas_miniodata:/data
      - atlas_minio_backup:/backup
    networks:
      - atlas-network
    ports:
      - "9010:9000"   # MinIO API
      - "9011:9001"   # MinIO console web

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    container_name: chromadb-atlas
    volumes:
      - atlas_chromadb_data:/chromadb
    networks:
      - atlas-network
    ports:
      - "8010:8000"