networks:
  atlas-net:
    external: true

services:
  atlas-llm-core:
    build: .
    container_name: atlas-llm-core-qa
    env_file: backend.qa.env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./:/app
      - ./models:/app/models
    ports:
      - "8035:8030"
    restart: unless-stopped
    networks:
      - atlas-net
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '16'
    #      memory: 24G